In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('imdb.csv')

In [3]:
df['Cast'] = df['Star1'] + ',' +df['Star2'] + ',' + df['Star3'] + ',' +df['Star4'] + ','

In [4]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross', 'Cast'],
      dtype='object')

In [5]:
columns = ['Certificate','Meta_score','Star1', 'Star2', 'Star3', 'Star4','Gross']

In [6]:
df= df.drop(columns=columns,axis=1)

In [7]:
df.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Runtime', 'Genre',
       'IMDB_Rating', 'Overview', 'Director', 'No_of_Votes', 'Cast'],
      dtype='object')

In [8]:

df = df[['Poster_Link', 'Series_Title', 'Released_Year', 'Runtime', 'Genre','IMDB_Rating', 'Overview', 'Director','Cast','No_of_Votes']]

In [9]:
df.head()

,Poster_Link,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Overview,Director,Cast,No_of_Votes
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845

In [10]:
df = df.rename(columns = {'Poster_Link':'Poster', 'Series_Title':'Title', 'Released_Year':'Year', 'Runtime':'Duration','IMDB_Rating':'Rating', 'No_of_Votes':'Votes'})

In [11]:
df.head()

,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845

In [12]:
df['Duration'] = df['Duration'].str.extract('(\d+)').astype(int)

In [13]:
df.head()

,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845

In [14]:
df.to_csv('Movieset.csv')

In [15]:
dff = pd.read_csv('Movieset.csv')

In [16]:
dff

,Unnamed: 0,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845
...,...,...,...,...,...,...,...,...,...,...,...
995,995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,115,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,Blake Edwards,"Audrey Hepburn,George Peppard,Patricia Neal,Bu...",166544
996,996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,201,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,George Stevens,"Elizabeth Taylor,Rock Hudson,James Dean,Carrol...",34075
997,997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,118,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,"Burt Lancaster,Montgomery Clift,Deborah Kerr,D...",43374
998,998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,97,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,"Tallulah Bankhead,John Hodiak,Walter Slezak,Wi...",26471
999,999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,86,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,Alfred Hitchcock,"Robert Donat,Madeleine Carroll,Lucie Mannheim,...",51853

In [17]:
dff = dff.rename(columns={'Unnamed: 0':'ID'})

In [18]:
dff.head()

,ID,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845

In [19]:
dff.set_index('ID')

,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
ID,,,,,,,,,,
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,142,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins,Morgan Freeman,Bob Gunton,William ...",2343110
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,Francis Ford Coppola,"Marlon Brando,Al Pacino,James Caan,Diane Keaton,",1620367
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale,Heath Ledger,Aaron Eckhart,Mich...",2303232
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino,Robert De Niro,Robert Duvall,Diane K...",1129952
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda,Lee J. Cobb,Martin Balsam,John Fie...",689845
...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,115,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,Blake Edwards,"Audrey Hepburn,George Peppard,Patricia Neal,Bu...",166544
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,201,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,George Stevens,"Elizabeth Taylor,Rock Hudson,James Dean,Carrol...",34075
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,118,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",Fred Zinnemann,"Burt Lancaster,Montgomery Clift,Deborah Kerr,D...",43374
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,97,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,Alfred Hitchcock,"Tallulah Bankhead,John Hodiak,Walter Slezak,Wi...",26471
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,86,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,Alfred Hitchcock,"Robert Donat,Madeleine Carroll,Lucie Mannheim,...",51853

In [22]:
dff.loc[df['Year']=='PG']

,ID,Poster,Title,Year,Duration,Genre,Rating,Overview,Director,Cast,Votes
966,966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,140,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,Ron Howard,"Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,",269197

In [23]:
dff.loc[df['Year']=='PG','Year']='1995'

In [24]:
dff.loc[966]

ID                                                        966
Poster      https://m.media-amazon.com/images/M/MV5BNjEzYj...
Title                                               Apollo 13
Year                                                     1995
Duration                                                  140
Genre                               Adventure, Drama, History
Rating                                                    7.6
Overview    NASA must devise a strategy to return Apollo 1...
Director                                           Ron Howard
Cast           Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,
Votes                                                  269197
Name: 966, dtype: object

In [25]:
dff['Year'] = dff['Year'].astype(int)

In [26]:
dff.to_csv('Movieset.csv')

In [27]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        1000 non-null   int64
 1   Poster    1000 non-null   object
 2   Title     1000 non-null   object
 3   Year      1000 non-null   int64
 4   Duration  1000 non-null   int64
 5   Genre     1000 non-null   object
 6   Rating    1000 non-null   float64
 7   Overview  1000 non-null   object
 8   Director  1000 non-null   object
 9   Cast      1000 non-null   object
 10  Votes     1000 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 86.1+ KB